spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/choice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/choice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: pynn2409!

  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  cache:
    type: redis
  redis:
    host: localhost
    # host: redis-13608.c244.us-east-1-2.ec2.cloud.redislabs.com
    port: 6379
    # 13608
    password: pynn2409!
  #    password: 6Owbxahfn3ju7qxXxPVUZrSNGDttrsFP
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

jwt:
  access-secret: zdeRaZg/EiMrAVuOX6pZeU5cdas5VqExPhTGje3dzIw=
  refresh-secret: 3Koh9ZqwkJOkjTSe1Y9k+r1gnTo8C5gPlAckjufNQYQ=

server:
  port: 81

coolsms:
  api-key: NCST2EVKTV0HLZ1N
  api-secret: R0TOE2O14T3XNR9ERFH7DIO6R0XY4AHR

cloud:
  aws:
    region:
      static : ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
      access-key: AKIARR5DC36KHY7S5KG4
      secret-key: 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
    s3:
      bucket: choice-bucket
      url: https://s3.ap-northeast-2.amazonaws.com/choice-bucket
