name: main YML

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 수동으로 해당 workflow 실행 지정
  workflow_dispatch:

# 현재 스크립트에서 사용할 환경변수를 정의하여 사용
env:
  S3_BUCKET_NAME: team-s3
  AWS_REGION: ap-northeast-2
  CODEDEPLOY_NAME: choic-application
  CODEDEPLOY_GROUP: choice-application-group

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
      # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE에서 저장소를 체크아웃합니다.
      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources/
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://team-s3/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name choic-application --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name choice-application-group --s3-location bucket=team-s3,bundleType=zip,key=$GITHUB_SHA.zip
        
